"""Reproduce ESA's SMART-1 Earth-escape spiral in GMAT from its real GTO.

SMART-1 (launched 2003-09-27 as an Ariane-5 auxiliary payload) reached
the Moon by spiralling out from a geostationary transfer orbit with a
single PPS-1350 Hall thruster over ~14 months. This script flies that
spiral in GMAT from the published initial orbit and hardware, under
real DE-series ephemerides (Earth 4x4 + Luna + Sun), and compares the
resulting transfer budget against the flown mission.

Published SMART-1 inputs (eoPortal / ESA / Milligan 2005):
  * GTO 654 x 35,885 km altitude, i = 7 deg (approximate; the actual injection
    was 742 x 36,016 km, ESA SMART-1 launch-phase page)
  * PPS-1350 Hall thruster: 88 mN, Isp 1650 s, ~1.9 kW
  * wet mass 367 kg, 82 kg xenon loaded (~75 kg used to the Moon)
  * ~14 months to lunar capture, ~3.5 km/s total (spiral + capture)

The spiral is flown with continuous tangential (+V) thrust -- SMART-1's
basic orbit-raising strategy -- until the osculating apogee reaches
lunar distance (~370,000 km), the natural Earth-escape handoff. The
Delta-v is recovered from the propellant consumed via the rocket
equation, so it is a genuine GMAT-measured budget, not an analytical
estimate. (The complementary analytical Edelbaum check is in
run_smart1_operating_point.py; the binary-QUBO capture endgame is in
run_gmat_capture_windows.py.)

Run:  python -m scripts.run_smart1_gmat_spiral
"""

from __future__ import annotations

import re
import subprocess
import tempfile
from pathlib import Path

import numpy as np

from qalunar.highfidelity import find_gmat_console


G0 = 9.80665

# --- Published SMART-1 reference -------------------------------------------
SMART1 = dict(
    gto_perigee_alt_km=654.0,
    gto_apogee_alt_km=35_885.0,
    inc_deg=7.0,
    thrust_mn=88.0,
    isp_s=1650.0,
    wet_mass_kg=367.0,
    xe_loaded_kg=82.0,
    xe_used_kg=75.0,
    tof_days=410.0,        # GTO insertion -> lunar capture (~13.5 months)
    dv_total_ms=3500.0,    # spiral + lunar capture
    power_kw=1.9,
)
EARTH_RADIUS_KM = 6_378.137
APOGEE_TARGET_KM = 370_000.0   # lunar-distance handoff
CHUNK_DAYS = 5.0
MAX_CHUNKS = 130               # 650-day safety cap


def _kepler_from_gto() -> tuple[float, float]:
    rp = EARTH_RADIUS_KM + SMART1["gto_perigee_alt_km"]
    ra = EARTH_RADIUS_KM + SMART1["gto_apogee_alt_km"]
    sma = 0.5 * (rp + ra)
    ecc = (ra - rp) / (ra + rp)
    return sma, ecc


def build_spiral_script(report_name: str) -> str:
    sma, ecc = _kepler_from_gto()
    chunk_s = CHUNK_DAYS * 86_400.0
    return f"""% Auto-generated by scripts/run_smart1_gmat_spiral.py
% SMART-1 Earth-escape spiral from its real GTO, continuous +V Hall thrust.

Create Spacecraft Smart1;
Smart1.DateFormat = UTCGregorian;
Smart1.Epoch = '28 Sep 2003 00:00:00.000';
Smart1.CoordinateSystem = EarthMJ2000Eq;
Smart1.DisplayStateType = Keplerian;
Smart1.SMA = {sma:.6f};
Smart1.ECC = {ecc:.8f};
Smart1.INC = {SMART1["inc_deg"]};
Smart1.RAAN = 0;
Smart1.AOP = 0;
Smart1.TA = 0;
Smart1.DryMass = {SMART1["wet_mass_kg"] - SMART1["xe_loaded_kg"]:.3f};
Smart1.Tanks = {{XeTank}};
Smart1.Thrusters = {{Hall}};
Smart1.PowerSystem = SolarP;

Create ElectricTank XeTank;
XeTank.AllowNegativeFuelMass = false;
XeTank.FuelMass = {SMART1["xe_loaded_kg"]:.3f};

Create ElectricThruster Hall;
Hall.CoordinateSystem = Local;
Hall.Origin = Earth;
Hall.Axes = VNB;
Hall.ThrustDirection1 = 1;
Hall.ThrustDirection2 = 0;
Hall.ThrustDirection3 = 0;
Hall.DecrementMass = true;
Hall.Tank = {{XeTank}};
Hall.ThrustModel = ConstantThrustAndIsp;
Hall.ConstantThrust = {SMART1["thrust_mn"] * 1e-3:.5f};
Hall.Isp = {SMART1["isp_s"]:.1f};
Hall.MaximumUsablePower = 2;
Hall.MinimumUsablePower = 0.01;

Create SolarPowerSystem SolarP;
SolarP.InitialMaxPower = {SMART1["power_kw"]:.2f};
SolarP.AnnualDecayRate = 0;
SolarP.Margin = 0;
SolarP.ShadowModel = 'None';

Create FiniteBurn Spiral;
Spiral.Thrusters = {{Hall}};

Create ForceModel FM;
FM.CentralBody = Earth;
FM.PrimaryBodies = {{Earth}};
FM.GravityField.Earth.Degree = 4;
FM.GravityField.Earth.Order = 4;
FM.PointMasses = {{Luna, Sun}};

Create Propagator Prop;
Prop.FM = FM;
Prop.Type = RungeKutta89;
Prop.InitialStepSize = 60;
Prop.Accuracy = 1e-10;
Prop.MinStep = 0;
Prop.MaxStep = 900;

Create ReportFile Rep;
Rep.Filename = '{report_name}';
Rep.Precision = 12;
Rep.WriteHeaders = false;

Create Variable goflag niter;

BeginMissionSequence;

Report Rep Smart1.ElapsedDays Smart1.Earth.SMA Smart1.Earth.RadApo Smart1.Earth.RadPer Smart1.XeTank.FuelMass Smart1.EarthMJ2000Eq.INC;

BeginFiniteBurn Spiral(Smart1);
goflag = 1;
niter = 0;
While goflag > 0.5
   Propagate Prop(Smart1) {{Smart1.ElapsedSecs = {chunk_s:.1f}}};
   niter = niter + 1;
   Report Rep Smart1.ElapsedDays Smart1.Earth.SMA Smart1.Earth.RadApo Smart1.Earth.RadPer Smart1.XeTank.FuelMass Smart1.EarthMJ2000Eq.INC;
   goflag = 0;
   If Smart1.Earth.RadApo < {APOGEE_TARGET_KM:.1f}
      goflag = 1;
   EndIf
   If Smart1.XeTank.FuelMass < 1
      goflag = 0;
   EndIf
   If niter > {MAX_CHUNKS}
      goflag = 0;
   EndIf
EndWhile
EndFiniteBurn Spiral(Smart1);
"""


def _run(script_text: str, report_name: str, console: Path,
         timeout: float = 1200.0) -> np.ndarray:
    with tempfile.NamedTemporaryFile(
        "w", suffix=".script", delete=False, encoding="ascii"
    ) as fh:
        fh.write(script_text)
        path = Path(fh.name)
    try:
        proc = subprocess.run(
            [str(console), str(path)], cwd=str(console.parent),
            capture_output=True, text=True, timeout=timeout,
        )
        raw = (proc.stdout or "") + (proc.stderr or "")
        if not re.search(r"Mission run completed", raw):
            raise RuntimeError("GMAT failed:\n"
                               + "\n".join(raw.splitlines()[-20:]))
        for d in (console.parent.parent / "output", console.parent / "output",
                  console.parent):
            p = d / report_name
            if p.exists():
                rows = [[float(v) for v in ln.split()]
                        for ln in p.read_text().strip().splitlines() if ln.strip()]
                p.unlink(missing_ok=True)
                return np.asarray(rows)
        raise FileNotFoundError(report_name)
    finally:
        path.unlink(missing_ok=True)


def _plot(log: np.ndarray, out_path: Path) -> None:
    import matplotlib
    matplotlib.use("Agg")
    import matplotlib.pyplot as plt

    t, sma, rapo, rper, fuel, inc = log.T
    fig, (ax1, ax2) = plt.subplots(
        1, 2, figsize=(12, 4.6), constrained_layout=True)

    ax1.plot(t, rapo / 1e3, color="#1f77b4", lw=1.8, label="apogee")
    ax1.plot(t, rper / 1e3, color="#d62728", lw=1.8, label="perigee")
    ax1.plot(t, sma / 1e3, color="#2ca02c", lw=1.2, ls="--", label="SMA")
    ax1.axhline(384.4, color="0.5", lw=1.0, ls=":", label="Moon distance")
    ax1.set_xlabel("days since GTO insertion")
    ax1.set_ylabel("Earth-relative radius (1000 km)")
    ax1.set_title("(a) SMART-1 orbit-raising spiral in GMAT")
    ax1.legend(loc="upper left", fontsize=8)
    ax1.grid(alpha=0.3)

    ax2.plot(t, SMART1["xe_loaded_kg"] - fuel, color="#9467bd", lw=1.8)
    ax2.set_xlabel("days since GTO insertion")
    ax2.set_ylabel("xenon consumed (kg)")
    ax2.set_title("(b) Propellant expenditure")
    ax2.grid(alpha=0.3)
    ax2.axhline(SMART1["xe_used_kg"], color="0.5", lw=1.0, ls=":",
                label=f"SMART-1 flown ({SMART1['xe_used_kg']:.0f} kg)")
    ax2.legend(loc="lower right", fontsize=8)

    fig.suptitle("Reproducing ESA SMART-1 from its real GTO with the qalunar "
                 "GMAT pipeline", fontsize=12)
    fig.savefig(out_path, dpi=180, bbox_inches="tight")
    print(f"  figure written to {out_path}")


def main() -> None:
    console = find_gmat_console()
    if not console.exists():
        raise SystemExit(f"GmatConsole not found at {console}")

    sma, ecc = _kepler_from_gto()
    print("=" * 84)
    print("  Reproducing SMART-1's Earth-escape spiral in GMAT (real GTO + "
          "PPS-1350 Hall)")
    print("=" * 84)
    print(f"  start: {SMART1['gto_perigee_alt_km']:.0f} x "
          f"{SMART1['gto_apogee_alt_km']:.0f} km altitude GTO, i={SMART1['inc_deg']}deg "
          f"(SMA {sma:,.0f} km, ECC {ecc:.4f})")
    print(f"  thrust {SMART1['thrust_mn']:.0f} mN, Isp {SMART1['isp_s']:.0f} s, "
          f"wet {SMART1['wet_mass_kg']:.0f} kg; spiral to "
          f"{APOGEE_TARGET_KM/1e3:.0f}e3 km apogee (lunar distance)\n")

    report = "smart1_spiral_report.txt"
    print("  flying the spiral in GMAT (continuous +V thrust) ...", flush=True)
    log = _run(build_spiral_script(report), report, console)

    t, smaa, rapo, rper, fuel, inc = log[-1]
    reached = rapo >= APOGEE_TARGET_KM * 0.98
    xe_used = SMART1["xe_loaded_kg"] - fuel
    m0, mf = SMART1["wet_mass_kg"], SMART1["wet_mass_kg"] - xe_used
    dv_ms = SMART1["isp_s"] * G0 * np.log(m0 / mf)

    print(f"\n  {'reached lunar-distance apogee' if reached else 'STOPPED (cap/fuel)'} "
          f"after {t:.0f} days")
    print(f"  final: apogee {rapo:,.0f} km, perigee {rper:,.0f} km, "
          f"SMA {smaa:,.0f} km, inc {inc:.2f} deg")
    print(f"  xenon used {xe_used:.1f} kg -> dV (rocket eq) {dv_ms:,.0f} m/s\n")

    print("-" * 84)
    print(f"  {'':<26}{'qalunar/GMAT':>16}{'SMART-1 flown':>16}")
    print(f"  {'spiral dV [m/s]':<26}{dv_ms:>16,.0f}"
          f"{SMART1['dv_total_ms']:>16,.0f}   (flown incl. capture)")
    print(f"  {'TOF to lunar dist [d]':<26}{t:>16,.0f}"
          f"{SMART1['tof_days']:>16,.0f}   (flown incl. capture)")
    print(f"  {'xenon used [kg]':<26}{xe_used:>16,.1f}"
          f"{SMART1['xe_used_kg']:>16,.1f}")
    print(f"  {'final inclination [deg]':<26}{inc:>16,.2f}"
          f"{SMART1['inc_deg']:>16,.2f}   (held ~constant)")
    print("-" * 84)
    print("  Note: GMAT figures are the Earth-escape spiral to lunar distance "
          "with 100%")
    print("  duty; SMART-1's flown 3.5 km/s and 410 d additionally include "
          "the lunar")
    print("  capture and ~40% thrust duty cycle (eclipses/power). The spiral "
          "dV is the")
    print("  thrust-independent Edelbaum invariant -- agreement here is the "
          "physics check.")

    out = Path(__file__).resolve().parent / "figures" / "smart1_gmat_spiral.png"
    out.parent.mkdir(parents=True, exist_ok=True)
    _plot(log, out)

    csv_out = out.with_suffix(".csv")
    np.savetxt(csv_out, log, delimiter=",",
               header="days,sma_km,rapo_km,rper_km,fuel_kg,inc_deg",
               comments="")
    print(f"  spiral log written to {csv_out}")


if __name__ == "__main__":
    main()
