"""Single continuous-trace GMAT visualisation of the full SMART-1 mission.

One spacecraft, one uninterrupted propagation from the real GTO to a bound
lunar orbit:

  Phase 1  tangential Hall thrust (Earth VNB +V) spirals out from the
           04 Oct 2003 GTO until the trajectory enters the lunar SOI;
  Phase 2  the SAME vehicle switches to anti-tangential braking
           (Moon VNB -V) and flies the binary-QUBO capture schedule
           (13 of 16 slots, from run_smart1_capture) that drops the
           Moon-relative energy below zero;
  Phase 3  a coast that shows the resulting (loose) bound lunar orbit.

Two OrbitViews render the single trace: an Earth-inertial view (the iconic
expanding spiral reaching the Moon) and a Moon-centred view (the capture
hook). Because it is one continuous propagation there is no phase seam --
exactly the "single trajectory" picture.

Open in the GMAT GUI (File > Open Script > Run), or:
    GMAT.exe --run scripts\\figures\\smart1_full_viz.script

Run:  python -m scripts.run_smart1_full_viz
"""

from __future__ import annotations

import csv
import re
import subprocess
import tempfile
from pathlib import Path

import numpy as np

from qalunar.highfidelity import find_gmat_console


EARTH_RADIUS_KM = 6_378.137
GTO_PERIGEE_ALT, GTO_APOGEE_ALT, INC_DEG = 654.0, 35_885.0, 7.0
THRUST_MN, ISP_S, DRY_MASS_KG, XE_LOADED_KG = 88.0, 1650.0, 285.0, 82.0
ENCOUNTER_EPOCH = "04 Oct 2003 00:00:00.000"
MOON_SOI_KM = 66_100.0
CAPTURE_WINDOW_DAYS = 3.0
N_SLOTS = 16
# Short: the one-pass capture is weak (E just below zero, apolune far
# outside the SOI), so over weeks Earth perturbs it back out -- a longer
# coast would render as a fly-away, not a capture. End the trace at the
# braking hook near the Moon; tightening to a held orbit needs multi-pass.
POST_COAST_DAYS = 11.0
FIG_DIR = Path(__file__).resolve().parent / "figures"


def _gto():
    rp, ra = EARTH_RADIUS_KM + GTO_PERIGEE_ALT, EARTH_RADIUS_KM + GTO_APOGEE_ALT
    return 0.5 * (rp + ra), (ra - rp) / (ra + rp)


def _capture_schedule() -> np.ndarray:
    csv_path = FIG_DIR / "smart1_capture.csv"
    if not csv_path.exists():
        raise SystemExit(f"{csv_path} not found; run run_smart1_capture first.")
    q = np.zeros(N_SLOTS, dtype=np.int64)
    with csv_path.open(newline="", encoding="utf-8") as fh:
        for row in csv.reader(fh):
            if row and row[0].isdigit():
                q[int(row[0])] = int(row[2])
    return q


def _capture_segments(schedule: np.ndarray) -> list[str]:
    dt = CAPTURE_WINDOW_DAYS * 86_400.0 / schedule.size
    lines, i = [], 0
    while i < schedule.size:
        b = int(schedule[i]); j = i
        while j < schedule.size and int(schedule[j]) == b:
            j += 1
        dur = (j - i) * dt
        if b == 1:
            lines += [
                "BeginFiniteBurn Brake(Sat);",
                f"Propagate Prop(Sat) {{Sat.ElapsedSecs = {dur:.4f}}};",
                "EndFiniteBurn Brake(Sat);",
            ]
        else:
            lines.append(f"Propagate Prop(Sat) {{Sat.ElapsedSecs = {dur:.4f}}};")
        i = j
    return lines


def build_script(report: str) -> str:
    sma, ecc = _gto()
    cap = _capture_segments(_capture_schedule())
    cap_str = "\n".join(cap)
    return f"""% Auto-generated by scripts/run_smart1_full_viz.py
% Full SMART-1 mission as a single continuous trace: spiral + capture.

Create CoordinateSystem MoonView;
MoonView.Origin = Luna;
MoonView.Axes = MJ2000Eq;

Create Spacecraft Sat;
Sat.DateFormat = UTCGregorian;
Sat.Epoch = '{ENCOUNTER_EPOCH}';
Sat.CoordinateSystem = EarthMJ2000Eq;
Sat.DisplayStateType = Keplerian;
Sat.SMA = {sma:.6f};
Sat.ECC = {ecc:.8f};
Sat.INC = {INC_DEG};
Sat.RAAN = 0;
Sat.AOP = 0;
Sat.TA = 0;
Sat.DryMass = {DRY_MASS_KG};
Sat.Tanks = {{XeTank}};
Sat.Thrusters = {{Hall, Brk}};
Sat.PowerSystem = SolarP;
Sat.OrbitColor = Cyan;

Create ElectricTank XeTank;
XeTank.AllowNegativeFuelMass = false;
XeTank.FuelMass = {XE_LOADED_KG};

Create ElectricThruster Hall;
Hall.CoordinateSystem = Local;
Hall.Origin = Earth;
Hall.Axes = VNB;
Hall.ThrustDirection1 = 1;
Hall.ThrustDirection2 = 0;
Hall.ThrustDirection3 = 0;
Hall.DecrementMass = true;
Hall.Tank = {{XeTank}};
Hall.ThrustModel = ConstantThrustAndIsp;
Hall.ConstantThrust = {THRUST_MN * 1e-3:.6f};
Hall.Isp = {ISP_S};
Hall.MaximumUsablePower = 2;
Hall.MinimumUsablePower = 0.01;

Create ElectricThruster Brk;
Brk.CoordinateSystem = Local;
Brk.Origin = Luna;
Brk.Axes = VNB;
Brk.ThrustDirection1 = -1;
Brk.ThrustDirection2 = 0;
Brk.ThrustDirection3 = 0;
Brk.DecrementMass = true;
Brk.Tank = {{XeTank}};
Brk.ThrustModel = ConstantThrustAndIsp;
Brk.ConstantThrust = {THRUST_MN * 1e-3:.6f};
Brk.Isp = {ISP_S};
Brk.MaximumUsablePower = 2;
Brk.MinimumUsablePower = 0.01;

Create SolarPowerSystem SolarP;
SolarP.InitialMaxPower = 1.9;
SolarP.AnnualDecayRate = 0;
SolarP.Margin = 0;
SolarP.ShadowModel = 'None';

Create FiniteBurn Spiral;
Spiral.Thrusters = {{Hall}};
Create FiniteBurn Brake;
Brake.Thrusters = {{Brk}};

Create ForceModel FM;
FM.CentralBody = Earth;
FM.PrimaryBodies = {{Earth}};
FM.GravityField.Earth.Degree = 4;
FM.GravityField.Earth.Order = 4;
FM.PointMasses = {{Luna, Sun}};

Create Propagator Prop;
Prop.FM = FM;
Prop.Type = RungeKutta89;
Prop.InitialStepSize = 60;
Prop.Accuracy = 1e-9;
Prop.MinStep = 0;
Prop.MaxStep = 1800;

Create OrbitView EarthView;
EarthView.SolverIterations = Current;
EarthView.UpperLeft = [0.01 0.01];
EarthView.Size = [0.6 0.95];
EarthView.Add = {{Sat, Earth, Luna}};
EarthView.CoordinateSystem = EarthMJ2000Eq;
EarthView.DrawObject = [true true true];
EarthView.ViewPointReference = Earth;
EarthView.ViewPointVector = [0 0 1300000];
EarthView.ViewDirection = Earth;
EarthView.ViewScaleFactor = 1;
EarthView.ViewUpCoordinateSystem = EarthMJ2000Eq;
EarthView.ViewUpAxis = X;
EarthView.Axes = On;
EarthView.XYPlane = On;

Create OrbitView MoonViewPort;
MoonViewPort.SolverIterations = Current;
MoonViewPort.UpperLeft = [0.62 0.01];
MoonViewPort.Size = [0.37 0.95];
MoonViewPort.Add = {{Sat, Luna}};
MoonViewPort.CoordinateSystem = MoonView;
MoonViewPort.DrawObject = [true true];
MoonViewPort.ViewPointReference = Luna;
MoonViewPort.ViewPointVector = [0 0 120000];
MoonViewPort.ViewDirection = Luna;
MoonViewPort.ViewScaleFactor = 1;
MoonViewPort.ViewUpCoordinateSystem = MoonView;
MoonViewPort.ViewUpAxis = X;
MoonViewPort.Axes = On;
MoonViewPort.XYPlane = Off;

Create ReportFile Rep;
Rep.Filename = '{report}';
Rep.Precision = 10;
Rep.WriteHeaders = false;

Create Variable goflag niter;

BeginMissionSequence;

% --- Phase 1: tangential spiral from GTO to the lunar SOI ---
BeginFiniteBurn Spiral(Sat);
goflag = 1;
niter = 0;
While goflag > 0.5
   Propagate Prop(Sat) {{Sat.ElapsedSecs = 43200}};
   niter = niter + 1;
   goflag = 0;
   If Sat.Luna.RMAG > {MOON_SOI_KM:.1f}
      goflag = 1;
   EndIf
   If niter > 320
      goflag = 0;
   EndIf
EndWhile
EndFiniteBurn Spiral(Sat);
Report Rep Sat.ElapsedDays Sat.Luna.RMAG Sat.Luna.Energy Sat.XeTank.FuelMass;

% --- Phase 2: anti-tangential binary-QUBO capture braking ---
{cap_str}
Report Rep Sat.ElapsedDays Sat.Luna.RMAG Sat.Luna.Energy Sat.XeTank.FuelMass;

% --- Phase 3: coast on the resulting bound lunar orbit ---
Propagate Prop(Sat) {{Sat.ElapsedSecs = {POST_COAST_DAYS * 86400.0:.1f}}};
Report Rep Sat.ElapsedDays Sat.Luna.RMAG Sat.Luna.Energy Sat.XeTank.FuelMass;
"""


def main() -> None:
    console = find_gmat_console()
    if not console.exists():
        raise SystemExit(f"GmatConsole not found at {console}")

    report = "smart1_full_viz_milestones.txt"
    script = build_script(report)
    out = FIG_DIR / "smart1_full_viz.script"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(script, encoding="ascii")
    print(f"  full-mission viz script written to {out}")

    print("  validating headless (full spiral + capture) ...", flush=True)
    with tempfile.NamedTemporaryFile("w", suffix=".script", delete=False,
                                     encoding="ascii") as fh:
        fh.write(script)
        tmp = Path(fh.name)
    try:
        proc = subprocess.run([str(console), str(tmp)], cwd=str(console.parent),
                              capture_output=True, text=True, timeout=900)
        raw = (proc.stdout or "") + (proc.stderr or "")
        if not re.search(r"Mission run completed", raw):
            raise SystemExit("GMAT failed:\n" + "\n".join(raw.splitlines()[-20:]))
        for d in (console.parent.parent / "output", console.parent / "output",
                  console.parent):
            p = d / report
            if p.exists():
                rows = [[float(v) for v in ln.split()]
                        for ln in p.read_text().strip().splitlines() if ln.strip()]
                p.unlink(missing_ok=True)
                labels = ["SOI entry", "after capture", "after coast"]
                for lab, r in zip(labels, rows):
                    print(f"    {lab:<14} day {r[0]:6.1f} | Moon {r[1]:8,.0f} km "
                          f"| E_moon {r[2]:+.4f} | Xe {r[3]:.1f} kg")
                break
    finally:
        tmp.unlink(missing_ok=True)

    print("\n  open in the GMAT GUI to watch the single continuous trace:")
    print(f'    GMAT.exe --run "{out}"')


if __name__ == "__main__":
    main()
